name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag platformio-docker-for-ci:test
    - name: Test to build example project inside container
      run: docker run -v ${pwd}/example:/opt/build --name pio-build platformio-docker-for-ci:test platformio run -d /opt/build/.
